# Generated by Django 2.2.8 on 2020-02-11 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Feedback',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_rating1', models.FloatField()),
                ('start_rating2', models.FloatField()),
                ('start_rating3', models.FloatField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Community_Class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Engagement_Period',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('communication_channel', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('engagement_period_multipler', models.IntegerField()),
                ('community_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cepf.Community_Class')),
                ('engagement_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cepf.Engagement_Period')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('appointment_feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cepf.Appointment_Feedback')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cepf.Community')),
                ('officers', models.ManyToManyField(to='cepf.Officer')),
            ],
        ),
    ]
