# Generated by Django 2.2.8 on 2020-02-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cepf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name_plural': 'Communities'},
        ),
        migrations.AlterModelOptions(
            name='community_class',
            options={'verbose_name_plural': 'Community_Classes'},
        ),
    ]
