# Generated by Django 3.0.3 on 2020-02-23 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cepf', '0002_auto_20200223_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.IntegerField()),
                ('reception', models.IntegerField()),
                ('impact', models.IntegerField()),
                ('notes', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Feedback',
                'db_table': 'Feedback',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cepf.Feedback'),
        ),
    ]
