# Generated by Django 2.2.8 on 2020-02-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cepf', '0002_auto_20200211_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment_feedback',
            options={'verbose_name_plural': 'Appointments_Feedback'},
        ),
        migrations.AlterModelOptions(
            name='engagement_period',
            options={'verbose_name_plural': 'Engagement_Periods'},
        ),
    ]
